version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edu_vexxel
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./database.db:/app/database.db
      - uploads_data:/app/static/uploads
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  uploads_data:
