"""Supabase integration with user modeling

Revision ID: a98eaec652fc
Revises: c8939be0ae3b
Create Date: 2025-11-11 17:46:23.656614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a98eaec652fc'
down_revision: Union[str, Sequence[str], None] = 'c8939be0ae3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('supabase_id', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_supabase_id'), 'user', ['supabase_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_supabase_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'supabase_id')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
